services:
  productclassification:
    build: .
    container_name: productclassification
    ports:
      - 8080:8080
    networks:
      - db-networks
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=user
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-networks

  ollamamodels:
    image: ollama/ollama
    container_name: ollamacontainer
    ports:
      - 11434:11434
    volumes:
      - ollama-models:/root/.ollama
      - ./ollamasetup.sh:/ollamasetup.sh:ro
    entrypoint: ["/bin/sh", "/ollamasetup.sh"]
    networks:
      - db-networks
  
volumes:
  db-data:
  ollama-models:

networks:
 db-networks: