services:
  productclassification:
    build: .
    container_name: productclassification
    ports:
      - 8080:8080
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - target: 5432
    volumes:
      - db-data:/var/lib/postgresql/data

  ollamamodels:
    image: ollama/ollama
    container_name: ollamacontainer
    ports:
      - target: 11434
    volumes:
      - ollama-models:/root/.ollama
      - ./ollamasetup.sh:/ollamasetup.sh
    entrypoint: [ "/bin/bash","/ollamasetup.sh" ]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-interface
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres-db

volumes:
  db-data:
  ollama-models:
