# specifying the Version key
version: '3.8'

# specifying the Services
services:

  # Name of the service
  db:
    # speciying the image name
    image: postgres:16.6-alpine3.20

    # giving the container name
    container_name: postgres-flask

    # exposing the ports
    ports:
      - "5432:5432"

    # setting the Environment values
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    
    # mounting the volume
    volumes:
      - db-data:/project:rw

  # another service name
  web-app:
    build: .
    container_name: flask-webapp
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - db-data:/project:rw
  
volumes:
  db-data: