services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
      DOTNET_RESOURCE_SERVICE_ENDPOINT_URL : "http://localhost:18888"
      Dashboard:ResourceServiceClient:AuthMode: "unsecured"
      DOTNET_ASPIRE_SHOW_DASHBOARD_RESOURCES : "true"
    ports:
    - target: 18888
      published: 18888
    restart: unless-stopped
  postgres:
    container_name: "postgres"
    image: "docker.io/postgres:16.6-alpine3.21"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "postgres"
    volumes:
    - "pgvol:/var/lib/postgresql/data"
    ports:
    - target: 5432
      published: 5432
    restart: unless-stopped
  ollama:
    container_name: "ollamatrail"
    image: "ollama/ollama:latest"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "ollama"
    volumes:
    - "ollmodels:/root/.ollama"
    - "../ollamasetup.sh:/ollamasetup.sh"
    ports:
    - target: 11434
      published: 11434
    entrypoint: ["/bin/sh","/ollamasetup.sh"]
    restart: unless-stopped
  products:
    container_name: "products"
    image: "products:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__productcontext: "Host=postgres;Port=5432;Username=user;Password=user;Database=productdb"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "products"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  migrationservice:
    container_name: "migrationservice"
    image: "migrationservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__productcontext: "Host=postgres;Port=5432;Username=user;Password=user;Database=productdb"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "migrationservice"
    restart: unless-stopped
  store:
    container_name: "store"
    image: "store:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      services__products__http__0: "http://products:8080"
      services__ollama__ollamaendpoint__0: "ollama:11434"
      SMTP_MAIL: "user"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "store"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
volumes:
  pgvol: {}
  ollmodels: {}
